### PR TITLE
Experimental APIs DEP draft

### PR DESCRIPTION
**Pull request by andrewgodwin**
First version of the Experimental DEPs draft. Comments both about formatting and content welcome.

### CODE REVIEW

**Comment by carltongibson** [comment]
Hey @andrewgodwin @jacobian — sorry for the archeology... 🫠 — To your recollection, was there a wider public discussion of this draft anywhere? Thanks.

**Comment by andrewgodwin** [comment]
I do not remember one!

**Comment by carltongibson** [comment]
OK, thanks for the confirmation @andrewgodwin 👍 (I'm not sure I remember anything at all from 2014)

**Comment by andrewgodwin** [comment]
Indeed, it was a while back. From my recollection, this was part of our push to try and make it easier to get things into core by having a lower bar for doing so, but the extent of how we framed it now eludes me.

**Comment by carltongibson** [comment]
@andrewgodwin thanks for the extra context. Somewhat ironically, that's the exact same conversation I'm back here digging it up for. I don't think you can get more Django than that 😅

**Pull request merged**
